# Generated by Django 4.2.8 on 2023-12-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_player_email_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Название игры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.game', verbose_name='Игра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
