# Generated by Django 4.2.8 on 2023-12-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_game_name_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='registration_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
