# Generated by Django 4.2.8 on 2023-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_game_is_drawn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
